# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

# db/seeds.rb
# NBA 2K26 Top 100 Players
# Run with: bin/rails db:seed

players = [
  { overall_rank: 1,   first_name: "Nikola",     last_name: "Jokic",                position: "C",     height: "6'11\"", team: "DEN", overall: 98, three_pt: 87, dunk: 75 },
  { overall_rank: 2,   first_name: "Shai",       last_name: "Gilgeous-Alexander",   position: "PG/SG", height: "6'6\"",  team: "OKC", overall: 98, three_pt: 82, dunk: 75 },
  { overall_rank: 3,   first_name: "Giannis",    last_name: "Antetokounmpo",        position: "PF/C",  height: "6'11\"", team: "MIL", overall: 97, three_pt: 75, dunk: 91 },
  { overall_rank: 4,   first_name: "Luka",       last_name: "Doncic",               position: "PG/SG", height: "6'6\"",  team: "LAL", overall: 97, three_pt: 87, dunk: 75 },
  { overall_rank: 5,   first_name: "Victor",     last_name: "Wembanyama",           position: "C/PF",  height: "7'3\"",  team: "SAS", overall: 96, three_pt: 81, dunk: 85 },
  { overall_rank: 6,   first_name: "Anthony",    last_name: "Edwards",              position: "SG/SF", height: "6'4\"",  team: "MIN", overall: 96, three_pt: 89, dunk: 97 },
  { overall_rank: 7,   first_name: "Stephen",    last_name: "Curry",                position: "PG/SG", height: "6'2\"",  team: "GSW", overall: 95, three_pt: 99, dunk: 36 },
  { overall_rank: 8,   first_name: "Donovan",    last_name: "Mitchell",             position: "SG/PG", height: "6'3\"",  team: "CLE", overall: 95, three_pt: 86, dunk: 92 },
  { overall_rank: 9,   first_name: "Jaylen",     last_name: "Brown",                position: "SF/PF", height: "6'6\"",  team: "BOS", overall: 95, three_pt: 80, dunk: 94 },
  { overall_rank: 10,  first_name: "Jayson",     last_name: "Tatum",                position: "PF/SF", height: "6'8\"",  team: "BOS", overall: 94, three_pt: 85, dunk: 89 },
  { overall_rank: 11,  first_name: "Kawhi",      last_name: "Leonard",              position: "SF/PF", height: "6'7\"",  team: "LAC", overall: 94, three_pt: 83, dunk: 80 },
  { overall_rank: 12,  first_name: "Cade",       last_name: "Cunningham",           position: "PG/SG", height: "6'6\"",  team: "DET", overall: 94, three_pt: 80, dunk: 75 },
  { overall_rank: 13,  first_name: "Jalen",      last_name: "Brunson",              position: "PG",    height: "6'2\"",  team: "NYK", overall: 93, three_pt: 86, dunk: 35 },
  { overall_rank: 14,  first_name: "Tyrese",     last_name: "Haliburton",           position: "PG/SG", height: "6'5\"",  team: "IND", overall: 93, three_pt: 84, dunk: 65 },
  { overall_rank: 15,  first_name: "Devin",      last_name: "Booker",               position: "PG/SG", height: "6'6\"",  team: "PHX", overall: 93, three_pt: 86, dunk: 75 },
  { overall_rank: 16,  first_name: "Tyrese",     last_name: "Maxey",                position: "PG/SG", height: "6'2\"",  team: "PHI", overall: 93, three_pt: 86, dunk: 70 },
  { overall_rank: 17,  first_name: "LeBron",     last_name: "James",                position: "PF/SF", height: "6'9\"",  team: "LAL", overall: 92, three_pt: 76, dunk: 85 },
  { overall_rank: 18,  first_name: "Kevin",      last_name: "Durant",               position: "SF/SG", height: "6'11\"", team: "HOU", overall: 92, three_pt: 90, dunk: 85 },
  { overall_rank: 19,  first_name: "Anthony",    last_name: "Davis",                position: "PF/C",  height: "6'10\"", team: "WAS", overall: 92, three_pt: 71, dunk: 85 },
  { overall_rank: 20,  first_name: "Joel",       last_name: "Embiid",               position: "C",     height: "7'0\"",  team: "PHI", overall: 92, three_pt: 74, dunk: 80 },
  { overall_rank: 21,  first_name: "Kyrie",      last_name: "Irving",               position: "PG/SG", height: "6'2\"",  team: "DAL", overall: 90, three_pt: 86, dunk: 30 },
  { overall_rank: 22,  first_name: "Jamal",      last_name: "Murray",               position: "PG/SG", height: "6'4\"",  team: "DEN", overall: 90, three_pt: 90, dunk: 82 },
  { overall_rank: 23,  first_name: "Karl-Anthony", last_name: "Towns",              position: "C/PF",  height: "7'0\"",  team: "NYK", overall: 89, three_pt: 83, dunk: 75 },
  { overall_rank: 24,  first_name: "James",      last_name: "Harden",               position: "PG/SG", height: "6'5\"",  team: "CLE", overall: 89, three_pt: 83, dunk: 75 },
  { overall_rank: 25,  first_name: "Trae",       last_name: "Young",                position: "PG",    height: "6'1\"",  team: "WAS", overall: 88, three_pt: 83, dunk: 30 },
  { overall_rank: 26,  first_name: "Bam",        last_name: "Adebayo",              position: "C/PF",  height: "6'9\"",  team: "MIA", overall: 88, three_pt: 79, dunk: 80 },
  { overall_rank: 27,  first_name: "Chet",       last_name: "Holmgren",             position: "PF/C",  height: "7'1\"",  team: "OKC", overall: 88, three_pt: 81, dunk: 75 },
  { overall_rank: 28,  first_name: "Damian",     last_name: "Lillard",              position: "PG",    height: "6'2\"",  team: "POR", overall: 88, three_pt: 86, dunk: 85 },
  { overall_rank: 29,  first_name: "Jimmy",      last_name: "Butler",               position: "PF/SF", height: "6'7\"",  team: "GSW", overall: 88, three_pt: 81, dunk: 75 },
  { overall_rank: 30,  first_name: "Austin",     last_name: "Reaves",               position: "SG/SF", height: "6'5\"",  team: "LAL", overall: 88, three_pt: 83, dunk: 70 },
  { overall_rank: 31,  first_name: "Deni",       last_name: "Avdija",               position: "SF/PG", height: "6'9\"",  team: "POR", overall: 88, three_pt: 79, dunk: 75 },
  { overall_rank: 32,  first_name: "Jalen",      last_name: "Johnson",              position: "PF/SF", height: "6'8\"",  team: "ATL", overall: 88, three_pt: 78, dunk: 96 },
  { overall_rank: 33,  first_name: "Ja",         last_name: "Morant",               position: "PG/SG", height: "6'2\"",  team: "MEM", overall: 87, three_pt: 72, dunk: 96 },
  { overall_rank: 34,  first_name: "Jalen",      last_name: "Williams",             position: "SF/PF", height: "6'5\"",  team: "OKC", overall: 87, three_pt: 79, dunk: 80 },
  { overall_rank: 35,  first_name: "Paolo",      last_name: "Banchero",             position: "PF/SF", height: "6'10\"", team: "ORL", overall: 87, three_pt: 78, dunk: 85 },
  { overall_rank: 36,  first_name: "Evan",       last_name: "Mobley",               position: "PF/C",  height: "6'11\"", team: "CLE", overall: 87, three_pt: 73, dunk: 85 },
  { overall_rank: 37,  first_name: "Pascal",     last_name: "Siakam",               position: "PF/C",  height: "6'8\"",  team: "IND", overall: 87, three_pt: 81, dunk: 80 },
  { overall_rank: 38,  first_name: "Alperen",    last_name: "Sengun",               position: "C/PF",  height: "6'11\"", team: "HOU", overall: 87, three_pt: 72, dunk: 80 },
  { overall_rank: 39,  first_name: "Zion",       last_name: "Williamson",           position: "PF/PG", height: "6'6\"",  team: "NOP", overall: 87, three_pt: 67, dunk: 93 },
  { overall_rank: 40,  first_name: "Franz",      last_name: "Wagner",               position: "SF/PF", height: "6'10\"", team: "ORL", overall: 87, three_pt: 80, dunk: 80 },
  { overall_rank: 41,  first_name: "Julius",     last_name: "Randle",               position: "PF/C",  height: "6'9\"",  team: "MIN", overall: 87, three_pt: 75, dunk: 80 },
  { overall_rank: 42,  first_name: "Scottie",    last_name: "Barnes",               position: "PF/PG", height: "6'7\"",  team: "TOR", overall: 87, three_pt: 75, dunk: 80 },
  { overall_rank: 43,  first_name: "Lauri",      last_name: "Markkanen",            position: "PF/SF", height: "7'0\"",  team: "UTA", overall: 87, three_pt: 83, dunk: 80 },
  { overall_rank: 44,  first_name: "Jalen",      last_name: "Duren",                position: "C",     height: "6'10\"", team: "DET", overall: 87, three_pt: 35, dunk: 95 },
  { overall_rank: 45,  first_name: "Cooper",     last_name: "Flagg",                position: "SF/PG", height: "6'9\"",  team: "DAL", overall: 87, three_pt: 75, dunk: 80 },
  { overall_rank: 46,  first_name: "Keyonte",    last_name: "George",               position: "PG/SG", height: "6'4\"",  team: "UTA", overall: 87, three_pt: 81, dunk: 65 },
  { overall_rank: 47,  first_name: "Jaren",      last_name: "Jackson Jr.",          position: "PF/C",  height: "6'10\"", team: "UTA", overall: 86, three_pt: 79, dunk: 80 },
  { overall_rank: 48,  first_name: "Domantas",   last_name: "Sabonis",              position: "C",     height: "6'10\"", team: "SAC", overall: 86, three_pt: 70, dunk: 75 },
  { overall_rank: 49,  first_name: "LaMelo",     last_name: "Ball",                 position: "PG/SG", height: "6'7\"",  team: "CHA", overall: 86, three_pt: 80, dunk: 75 },
  { overall_rank: 50,  first_name: "Amen",       last_name: "Thompson",             position: "SG/PG", height: "6'7\"",  team: "HOU", overall: 86, three_pt: 58, dunk: 96 },
  { overall_rank: 51,  first_name: "Tyler",      last_name: "Herro",                position: "SG/PG", height: "6'5\"",  team: "MIA", overall: 86, three_pt: 83, dunk: 60 },
  { overall_rank: 52,  first_name: "De'Aaron",   last_name: "Fox",                  position: "PG/SG", height: "6'3\"",  team: "SAS", overall: 86, three_pt: 78, dunk: 80 },
  { overall_rank: 53,  first_name: "Brandon",    last_name: "Ingram",               position: "SF/PF", height: "6'8\"",  team: "TOR", overall: 86, three_pt: 79, dunk: 80 },
  { overall_rank: 54,  first_name: "Norman",     last_name: "Powell",               position: "SF/SG", height: "6'4\"",  team: "MIA", overall: 86, three_pt: 86, dunk: 80 },
  { overall_rank: 55,  first_name: "Michael",    last_name: "Porter Jr.",           position: "SF/PF", height: "6'10\"", team: "BKN", overall: 86, three_pt: 85, dunk: 80 },
  { overall_rank: 56,  first_name: "Brandon",    last_name: "Miller",               position: "SG/SF", height: "6'7\"",  team: "CHA", overall: 86, three_pt: 81, dunk: 87 },
  { overall_rank: 57,  first_name: "Trey",       last_name: "Murphy III",           position: "SG/SF", height: "6'8\"",  team: "NOP", overall: 86, three_pt: 81, dunk: 88 },
  { overall_rank: 58,  first_name: "Ivica",      last_name: "Zubac",                position: "C",     height: "7'0\"",  team: "IND", overall: 85, three_pt: 26, dunk: 80 },
  { overall_rank: 59,  first_name: "Derrick",    last_name: "White",                position: "SG/PG", height: "6'4\"",  team: "BOS", overall: 85, three_pt: 77, dunk: 55 },
  { overall_rank: 60,  first_name: "OG",         last_name: "Anunoby",              position: "SF/PF", height: "6'7\"",  team: "NYK", overall: 85, three_pt: 81, dunk: 85 },
  { overall_rank: 61,  first_name: "Rudy",       last_name: "Gobert",               position: "C",     height: "7'1\"",  team: "MIN", overall: 85, three_pt: 25, dunk: 75 },
  { overall_rank: 62,  first_name: "Jarrett",    last_name: "Allen",                position: "C",     height: "6'9\"",  team: "CLE", overall: 85, three_pt: 63, dunk: 85 },
  { overall_rank: 63,  first_name: "Stephon",    last_name: "Castle",               position: "SG/PG", height: "6'6\"",  team: "SAS", overall: 85, three_pt: 73, dunk: 88 },
  { overall_rank: 64,  first_name: "Josh",       last_name: "Giddey",               position: "PG/SG", height: "6'8\"",  team: "CHI", overall: 85, three_pt: 81, dunk: 65 },
  { overall_rank: 65,  first_name: "Shaedon",    last_name: "Sharpe",               position: "SG/PG", height: "6'5\"",  team: "POR", overall: 85, three_pt: 76, dunk: 95 },
  { overall_rank: 66,  first_name: "Kon",        last_name: "Knueppel",             position: "SF/SG", height: "6'7\"",  team: "CHA", overall: 85, three_pt: 92, dunk: 55 },
  { overall_rank: 67,  first_name: "Dillon",     last_name: "Brooks",               position: "PF/SF", height: "6'6\"",  team: "PHX", overall: 85, three_pt: 80, dunk: 75 },
  { overall_rank: 68,  first_name: "Darius",     last_name: "Garland",              position: "PG/SG", height: "6'1\"",  team: "LAC", overall: 84, three_pt: 84, dunk: 40 },
  { overall_rank: 69,  first_name: "DeMar",      last_name: "DeRozan",              position: "SF/PF", height: "6'6\"",  team: "SAC", overall: 84, three_pt: 77, dunk: 80 },
  { overall_rank: 70,  first_name: "Kristaps",   last_name: "Porzingis",            position: "C/PF",  height: "7'2\"",  team: "GSW", overall: 84, three_pt: 80, dunk: 75 },
  { overall_rank: 71,  first_name: "Mikal",      last_name: "Bridges",              position: "SG/SF", height: "6'6\"",  team: "NYK", overall: 84, three_pt: 82, dunk: 75 },
  { overall_rank: 72,  first_name: "Desmond",    last_name: "Bane",                 position: "SG/SF", height: "6'5\"",  team: "ORL", overall: 84, three_pt: 84, dunk: 75 },
  { overall_rank: 73,  first_name: "Aaron",      last_name: "Gordon",               position: "PF/C",  height: "6'8\"",  team: "DEN", overall: 84, three_pt: 84, dunk: 94 },
  { overall_rank: 74,  first_name: "Immanuel",   last_name: "Quickley",             position: "PG/SG", height: "6'2\"",  team: "TOR", overall: 84, three_pt: 80, dunk: 55 },
  { overall_rank: 75,  first_name: "Alexandre",  last_name: "Sarr",                 position: "C/PF",  height: "7'0\"",  team: "WAS", overall: 84, three_pt: 78, dunk: 85 },
  { overall_rank: 76,  first_name: "Donovan",    last_name: "Clingan",              position: "C",     height: "7'2\"",  team: "POR", overall: 84, three_pt: 75, dunk: 75 },
  { overall_rank: 77,  first_name: "Zach",       last_name: "LaVine",               position: "SG/SF", height: "6'5\"",  team: "SAC", overall: 83, three_pt: 86, dunk: 94 },
  { overall_rank: 78,  first_name: "Dyson",      last_name: "Daniels",              position: "SG/PG", height: "6'7\"",  team: "ATL", overall: 83, three_pt: 50, dunk: 75 },
  { overall_rank: 79,  first_name: "Naz",        last_name: "Reid",                 position: "C/PF",  height: "6'9\"",  team: "MIN", overall: 83, three_pt: 83, dunk: 80 },
  { overall_rank: 80,  first_name: "Nikola",     last_name: "Vucevic",              position: "C",     height: "6'10\"", team: "BOS", overall: 83, three_pt: 81, dunk: 65 },
  { overall_rank: 81,  first_name: "Jalen",      last_name: "Suggs",                position: "PG/SG", height: "6'5\"",  team: "ORL", overall: 83, three_pt: 78, dunk: 80 },
  { overall_rank: 82,  first_name: "Isaiah",     last_name: "Hartenstein",          position: "C",     height: "7'0\"",  team: "OKC", overall: 83, three_pt: 55, dunk: 80 },
  { overall_rank: 83,  first_name: "Jaden",      last_name: "McDaniels",            position: "SF/PF", height: "6'9\"",  team: "MIN", overall: 83, three_pt: 86, dunk: 75 },
  { overall_rank: 84,  first_name: "Walker",     last_name: "Kessler",              position: "C",     height: "7'0\"",  team: "UTA", overall: 83, three_pt: 70, dunk: 75 },
  { overall_rank: 85,  first_name: "Jrue",       last_name: "Holiday",              position: "PG/SG", height: "6'4\"",  team: "POR", overall: 83, three_pt: 80, dunk: 65 },
  { overall_rank: 86,  first_name: "C.J.",       last_name: "McCollum",             position: "PG/SG", height: "6'3\"",  team: "ATL", overall: 83, three_pt: 84, dunk: 40 },
  { overall_rank: 87,  first_name: "Nickeil",    last_name: "Alexander-Walker",     position: "PG/SG", height: "6'5\"",  team: "ATL", overall: 83, three_pt: 82, dunk: 60 },
  { overall_rank: 88,  first_name: "Peyton",     last_name: "Watson",               position: "SF/PF", height: "6'7\"",  team: "DEN", overall: 83, three_pt: 85, dunk: 65 },
  { overall_rank: 89,  first_name: "Anthony",    last_name: "Black",                position: "PG/SG", height: "6'7\"",  team: "ORL", overall: 83, three_pt: 78, dunk: 75 },
  { overall_rank: 90,  first_name: "Ausar",      last_name: "Thompson",             position: "SF/PF", height: "6'6\"",  team: "DET", overall: 83, three_pt: 72, dunk: 91 },
  { overall_rank: 91,  first_name: "Grayson",    last_name: "Allen",                position: "SG/SF", height: "6'4\"",  team: "PHX", overall: 83, three_pt: 86, dunk: 70 },
  { overall_rank: 92,  first_name: "Payton",     last_name: "Pritchard",            position: "PG",    height: "6'1\"",  team: "BOS", overall: 83, three_pt: 78, dunk: 35 },
  { overall_rank: 93,  first_name: "R.J.",       last_name: "Barrett",              position: "SG/SF", height: "6'6\"",  team: "TOR", overall: 82, three_pt: 78, dunk: 80 },
  { overall_rank: 94,  first_name: "Toumani",    last_name: "Camara",               position: "PF/SF", height: "6'7\"",  team: "POR", overall: 82, three_pt: 79, dunk: 75 },
  { overall_rank: 95,  first_name: "Josh",       last_name: "Hart",                 position: "PF/SF", height: "6'4\"",  team: "NYK", overall: 82, three_pt: 83, dunk: 70 },
  { overall_rank: 96,  first_name: "Paul",       last_name: "George",               position: "PF/SF", height: "6'8\"",  team: "PHI", overall: 82, three_pt: 82, dunk: 80 },
  { overall_rank: 97,  first_name: "Onyeka",     last_name: "Okongwu",              position: "C",     height: "6'10\"", team: "ATL", overall: 82, three_pt: 80, dunk: 85 },
  { overall_rank: 98,  first_name: "Andrew",     last_name: "Nembhard",             position: "PG/SG", height: "6'4\"",  team: "IND", overall: 82, three_pt: 80, dunk: 60 },
  { overall_rank: 99,  first_name: "Jerami",     last_name: "Grant",                position: "PF/SF", height: "6'7\"",  team: "POR", overall: 82, three_pt: 81, dunk: 85 },
  { overall_rank: 100, first_name: "Mark",       last_name: "Williams",             position: "C",     height: "7'0\"",  team: "PHX", overall: 82, three_pt: 36, dunk: 75 },
]

puts "Seeding #{players.size} players..."

players.each do |attrs|
  Player.find_or_create_by(overall_rank: attrs[:overall_rank]).update!(attrs)
end

puts "Done! #{Player.count} players in database."
